### ISSUE TITLE
Summer(?) plans

### ISSUE THREAD

**Issue by dktcoding** [kronenthaler/libai#18]
I've been drafting a small plan for my involvement over the summer (summer in Argentina...) in `libai` (needless to say I'll keep collaborating afterwards, just not so much).

- Make JavaDoc compile without warnings (I'll do this today)
- Add extra activation functions
- Write some integration tests for MLP, SVM and DFS (we'll need a special thread for this, but I think that we can do something relatively good using the current demos)
- Start drafting a Wiki (there's some interest in `libai` and this will help start things up, again based on the demos)
- Draft and implement a standard way to do filtering and sorting in `DataSet`
- Generalize a bit `TextFileDataSet` (tsv, quoted text, etc)
- Export matrices in [`.bin`](http://octave.1599824.n4.nabble.com/Octave-binary-format-td1607907.html) format 

If there's time, add input validation for all the public *high level* methods (I've been doing some profiling and it really degradates the `Matrix` class, so there, I'll just make some more verbose asserts)

This are some things that **I** need, but if there's something else, or something superfluous let me know (my "original" plan was almost 200 lines... but I need to be realistic on my "free-time" expectations)

**Comment by kronenthaler** [comment]
Sounds good to me man, myself i'm focusing on to finish another project that needed a lot of love, once i'm done with it, i'll spend some time on this one again. I created a project board, so feel free to create issues there, so i can pick up some of them when ready. 

I can see your main interest is in the neural networks, if i were you, i would let out any work not related to the NN, like the data sets. I also have some personal interest into improve that implementation, and provide a better integration with the NN package, so it might take some refactors in the near future.

**Comment by dktcoding** [comment]
You are right, my main interest is NN, but I have been playing around with some of the "other" `libai` algorithm implementations and well... it all kinda... snowballed.

I'll start working on saving `Matrix` objects as `.bin` and `.mat` files for now to allow integration with GNU Octave/Matlab, then a small break, and then we'll see were we go from there.
