### ISSUE TITLE
MLP backpropagation parameters

### ISSUE THREAD

**Issue by dktcoding** [kronenthaler/libai#25]
I'd started reviewing the MLP class, and there are a couple of things that I need clarification/advice on:

- I was thinking adding the proper parameters to the back-propagation algorithms (for instance RProp has a lot of default values), the thing is, there are a lot of ways of doing this, and wondered which seems best: 
  - integer constants for each param index and keep using the param array (this will create a LOT of constants, and a problem with default values) 
  - use an enum set with the _non-default_ values
  - create a class for each back-propagation with it own set of properties
  - other...
- Given that the Iris dataset is already in the project I was planning on creating integration tests with it, particularly since (as far as I remember) it even had a couple of linearly separable features.
- About input validation, I'm assuming `IllegalArgumentException`s are ok?

**Comment by kronenthaler** [comment]
The internal parameters on Rprog (Nplus, Nminus, MaxUpdate, MinUpdate, InitialUpdate), those values were taken from the paper of Rprog. I would have to check the paper again to see if there is any real reason to allow customization on those parameters. I personally don't think they should be configurable. It would require lots of knowledge about the algorithm itself to tweak properly.

On the other hand, allowing tweak on those parameters could be good for hybrid approaches, where the genetic or fuzzy system calculates them and feed them to the network.

I have a issue open to think about a better way to pass parameters to the neural networks via a parameter class. I think a parameter object will allow to do this in a more cleaner way. But i need to give it a thought.

**Comment by kronenthaler** [comment]
I mentioned on one of the PR's comment, maybe we can create an abstraction Backpropagation, and implement the different algorithms (each with their set of parameters) and it must have to be a MLP's constructor parameter an instance of Backpropagation, we could "default it" to the StandardBackpropagation implementation.

**Comment by dktcoding** [comment]
That sound like a good idea, given that the signature of all backprop algorithms are the same it shouldn't be too hard to implement.
