### ISSUE TITLE
Removing Netbeans dependency

### ISSUE THREAD

**Issue by dktcoding** [kronenthaler/libai#30]
Tasks to be done before removing Netbeans:

- [x] create all `ant` scripts (or `mvn`, or both)
- [x] make sure everything compiles (JavaDoc, Code, Tests) with no missing dependencies
- [x] executing the jar should open the demos
- [ ] extract `demos` to other project:
  - Demos are the only thing really depending on Netbeans
  - Matisse GUIs can't be externally edited (can... but bad things usually happen)
  - Demos are amazing and they must be preserved

**Comment by kronenthaler** [comment]
I would like to keep the demo in the project as it's the easiest way to show functionality. Maybe refactor the demos to make them netbeans independent? Starting by remove the Matisse's XMLs and leave the plain ugly generated code for the moment, and we refactor it later on ?

**Comment by dktcoding** [comment]
I thought about it, but seems kinda crude. I'll see what happens if I remove all the rest of the Netbeans folders and leave the form files, perhaps it's possible to still use Netbeans to edit them (I'm not entirely sure).
