### ISSUE TITLE
About NeuralNetwork#open()

### ISSUE THREAD

**Issue by dktcoding** [kronenthaler/libai#50]
There's an issue regarding `NeuralNetwork#open()`, could we:
1. Implement it in `NeuralNetwork` (just as `save()`)?
1. Throw an exception instead of simply returning `null` and polluting the output with `Exception#printStackTrace()`?

The user will be responsible for casting, but still seems like a better idea than having a lot of repeated code.

Perhaps an alternative could be to create a `NeuralNetworkIO` class.

**Comment by kronenthaler** [comment]
The main reason why the open method is not in the abstract class is that, static methods cannot be abstract. The reasoning behind having the open method static is to avoid the creation of an "empty" NN that will be populated later on during the load. It seems more clear to use as 
`Adaline.open("file")` or `MLP.open("file")`, no dummy objects are created, instead the object is returned on the opening.

I don't think the NNIO class is a good idea, i'm more inclined to is to create something like this:

```
class NeuralNetwork { 
public static <NN extends NeuralNetwork> NN open(String file){
  try{ 
    ... 
    return (NN)in.readObject();
  }catch(IOException e){
    return null;
  }
}
```

**Comment by dktcoding** [comment]
I been thinking of a couple of alternatives for this, all of them have their ups and downs:
```Java
public static <T extends NeuralNetwork>T open(String path, T obj) {
    try (FileInputStream fis = new FileInputStream(path);
         ObjectInputStream in = new ObjectInputStream(fis)){
        return (T)in.readObject() ;
    } catch (Exception e) {
        return null;
    }
}
```
The biggest downside of this is that we need an instance of `T`, which doesn't make much sense.

```Java
public static NeuralNetwork open(String path, Class<? extends NeuralNetwork> obj) {
    try (FileInputStream fis = new FileInputStream(path);
         ObjectInputStream in = new ObjectInputStream(fis)){
        return obj.cast(in.readObject());
    } catch (Exception e) {
        return null;
    }
}
```
In this one we still need to recast after opening, but we can guarantee that the object is of the specified class.

```Java
public static NeuralNetwork open(String path) {
    try (FileInputStream fis = new FileInputStream(path);
         ObjectInputStream in = new ObjectInputStream(fis)){
        return (NeuralNetwork)in.readObject();
    } catch (Exception e) {
        return null;
    }
}
```
This is the most simple scenario, basically the same as before, but with a chance of `ClassCastException`.

```Java
public static NeuralNetwork open(FileInputStream fis) throws Exception {
    try (ObjectInputStream in = new ObjectInputStream(fis)){
        return (NeuralNetwork)in.readObject();
    }
}
```
This last one is the one I'm currently using.

---
So:
1. Which? (if any)
1. Should we keep using `String path` or `InputStream in`
1. Throw the exception of fail silently?

Honestly the thing I care the most is changing paths to `Input/Output Stream` and removing the `ex.printStackTrace()` from the `open()` implementation.

But given that I'm not the only user of `libai` this should be sufficiently general (particularly since IO changes tend to "break" things in an ulgy way...).

PS: I'll be travelling in a couple of days so might be unresposive for a week or so

**Comment by kronenthaler** [comment]
Hey, i tested the snippet i suggested and removed the open method of all the classes, the unit tests don't fail at all, the compiler solves the problem brilliantly. I don't understand why so much trouble with the solution. 
Regarding the stacktrace, i see 3 options:

1. return null and print the stacktrace 
2. return null and not print the stacktrace (which is kind of i failed but go figure it out yourself)
3. change the method to throws IOException and not return null if there is a failure, and let the developer deal with it.

Approach 2 seems like a bad practice for me, i'm more inclined now to approach 3 as it provides information but delegates the handling of the error to the developer.

As of the input parameter, we could overload it like in many other java APIs do:
- `open (String path)`
- `open (File path)`
- `open (InputStream input)`

At the end the actual implementation will be only one of them and the other 2 will be aliases to the actual implementation.

**Comment by kronenthaler** [comment]
PR #56 contains this changes.

**Comment by dktcoding** [comment]
You are of course right... but honestly, I couldn't make it work. I've been looking at it for a while and can't really understand why it didn't work in the first place *sigh* anyhow...

I too much rather have option 3 as well, let the developer handle the exception (this applies to all IO methods).
